apiVersion: v1
kind: Pod
metadata:
  name: luckynumbernamepod1
  labels:
    app: luckynumberapp1
spec:
  containers:
  - name: luckynumber
    image: quocit/luckynumber:tagname
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80