apiVersion: v1
kind: Pod
metadata:
  name: aspnetappdemo1
  labels:
    app: aspnetappdemo1
spec:
  containers:
  - name: aspname
    image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80