apiVersion: v1
kind: Pod
metadata:
  name: luckynumbernamepod3
  labels:
    app: luckynumberapp3
spec:
  containers:
  - name: luckynumber
    image: quocit/luckynumber:latest1
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80