apiVersion: v1
kind: Pod
metadata:
  name: demoaspnetname
  labels:
    app: demoaspnetapp
spec:
  containers:
  - name: aspnamedemo
    image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80